t1: Correct, answer was 52
t2: Correct, answer was not well-formed
t3: Correct, answer was 52 42
t4: Correct, answer was syntax error
t5: Correct, answer was 0 -420
t6: Correct, answer was 5 0
t7: Correct, answer was -18 -330
t8: Correct, answer was 70
t9: Correct, answer was syntax error
t10: Correct, answer was syntax error
t11: Correct, answer was 528
t12: Correct, answer was 1
t13: Correct, answer was 11
t14: Correct, answer was not well-formed
t15: Correct, answer was type error
t16: Correct, answer was 0
t17: Correct, answer was 42 0
t18: Correct, answer was type error
t19: Correct, answer was -30
t21: Correct, answer was declare-first error
t22: Correct, answer was 42 10 42
t23: Correct, answer was 42
t24: Correct, answer was 0 1 2
t25: Correct, answer was 0 1 2
t26: Correct, answer was 1 2 3 4
t27: Correct, answer was Proto Runtime Error: Attempt to access array out of bounds
t28: Correct, answer was 42 42
t29: Correct, answer was 42 41
t30: Correct, answer was 42 41
t31: Correct, answer was 24 42 42
t32: Correct, answer was syntax error
t33: Correct, answer was 1 1 1
t34: Correct, answer was Proto Runtime Error: Attempt to access array out of bounds
t35: Correct, answer was syntax error
t36: Correct, answer was not well-formed
t37: Correct, answer was not well-formed
t38: Correct, answer was type error
t39: Correct, answer was type error
t40: Correct, answer was type error
t41: Correct, answer was type error
t42: Correct, answer was type error
t43: Correct, answer was type error
t44: Correct, answer was type error
t45: Correct, answer was type error
t46: Correct, answer was type error
t47: Correct, answer was type error
t48: Correct, answer was type error
t49: Correct, answer was type error
t50: Correct, answer was type error
t51: Correct, answer was type error
t52: Correct, answer was type error
t53: Correct, answer was type error
t54: Correct, answer was type error
t55: Correct, answer was type error
t56: Correct, answer was type error
t57: Correct, answer was type error
t58: Correct, answer was type error
t59: Correct, answer was not well-formed
t60: Wrong, erroneously detected a syntax error, answer should be 0 1 2 3 4 5 6 7 8 9
t61: Correct, answer was 42 43
t62: Correct, answer was 41 42
t63: Wrong, erroneously detected a syntax error, answer should be 38 40 42
t64: Correct, answer was 1 3 5 7 9 11 13 15 17 19
t65: Correct, answer was 42
t66: Correct, answer was 42
t67: Correct, answer was 42
t68: Correct, answer was not well-formed
t69: Correct, answer was 42
t70: Correct, answer was not well-formed
t71: Correct, answer was type error in assignment
t72: See comment #2, answer was type error in method call
t73: Correct, answer was type error in this
t74: Correct, answer was type error in super
t75: Correct, answer was 41 42 43
t76: Correct, answer was 41 42 53
t77: Correct, answer was type error in array subtype
t78: Correct, answer was 1 3 5
t79: Wrong, erroneously detected a type error, should be 0 1 2 3 4 5
t80: Wrong, erroneously detected a 'redeclaration', answer should be
42 (overriding)
t81: Correct, answer was 42 52
t82: Correct, answer was 52 42
t83: Correct, answer was 42 11
t84: Correct, answer was 0


Syntax Checking  :  1.5/2
Static Semantics :  
Non-Class types : 5/5
	Inheritance : 4.5/5
	Overriding : 2.5/3
Dynamic Semantics : 
	Use of inherited fields : 4/4
	Calls to inherited methods : 4/4
	Overloaded methods : 4/4
	Other remaining constructs : 3/3
Total : 29/30

Comments:
1. Fantastic job, once again!
2. I got the following python error:
Traceback (most recent call last):
  File "protoplasm5.py", line 112, in <module>
    main(args)
  File "protoplasm5.py", line 41, in main
    program = parser.parse(open(args.file, 'r').read())
  File "/Users/spyros/SUNYSB/CSE504/temp3/biondo-kasiak/HW6/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Users/spyros/SUNYSB/CSE504/temp3/biondo-kasiak/HW6/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/Users/spyros/SUNYSB/CSE504/temp3/biondo-kasiak/HW6/proto5parser.py", line 517, in p_error
    p.lexer.proto_errors += 1
AttributeError: 'NoneType' object has no attribute 'lexer'
